version: '3.8'
services:
    server:
        build: .
        volumes:
            - ./data:/app/data
            - ./html:/app/html
        env_file:
            - .env
        ports:
            - "80"
            - "443"
        restart: unless-stopped